service: serverless-rest-apis-user

provider: 
  name: aws
  runtime: nodejs6.10
  environment: 
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: users/create.create
    events:
      - http:
          path: users
          method: post
          corn: true

  list:
    handler: users/list.list
    events: 
      - http:
          path: users
          method: get
          corn: true

  update:
    handler: users/update.update
    events:
      - http:
          path: users/{id}
          method: put
          corn: true

  get:
    handler: users/get.get
    events:
      - http:
          path: users/{id}
          method: get
          corn: true

  delete:
    handler: users/delete.delete
    events:
      - http:
          method: delete
          path: users/{id}
          corn: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}